### ISSUE TITLE
Example won't work(No any response after pushing the download button)

### ISSUE THREAD

**Issue by kleon1024** [fluttercommunity/flutter_downloader#214]
Hi,
    I'm trying to build and run example. But I get no response after pushing the download button except a line of "Download task is enqueued with id(a7e47c25-4fc0-4f16-ae47-4b9914d5a77f)".

I'm using Flutter  v1.12.13+hotfix.5(the latest stable channel), and testing both on a phone with Andriod 9 and an emulator with API 28.

Is there any prerequisites?

Any response will be helpful, thanks.

**Comment by hnvn** [comment]
It happens because of changes in Android V2 embedding. I am working on it. For now, you can try on the working branch: embedding-v2
```yaml
flutter_downloader:
   git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2
```
