### ISSUE TITLE
Flutter Downloader download image in android emulator but show failed in real device

### ISSUE THREAD

**Issue by thetestcoder** [fluttercommunity/flutter_downloader#381]
hi, 

I working on app that download image from server and store in external storage download folder. When i try to download image in android emulator its working fine but after build apk and run on real device its show failed.

## using 

```

environment:
  sdk: ">=2.7.0 <3.0.0"

  shared_preferences: 0.5.8
  esys_flutter_share: ^1.0.2
  shimmer:
  clipboard: ^0.1.2+8
  flutter_redux: 0.6.0
  redux_thunk: 0.3.0
  filter_list: ^0.0.4
  redux_logging: 0.4.0
  flutter_downloader: 1.5.2
  ext_storage: 1.0.3
  permission_handler: 5.0.1+1
  path_provider: 1.6.14
  numeral:
  http:
  cached_network_image: ^2.3.1
  flutter_swiper:
  flutter_icons: ^1.1.0
```

## Here is my Code

```
_getPathToDownload() async {
    return ExtStorage.getExternalStoragePublicDirectory(ExtStorage.DIRECTORY_DOWNLOADS);
  }

_onDownload(image) async {
    final imgUrl = "server-url";
    var dir = await _getPathToDownload();
    final taskId = await FlutterDownloader.enqueue(
      url: imgUrl,
      savedDir: dir,
      fileName: "${image.title}.jpg",
      showNotification: true, 
      openFileFromNotification: true,
    );
  }
```
